on:
jobs:
name: NetfleetGPT Sync
on:
  repository_dispatch:
    types: [netfleetgpt_push]
  workflow_dispatch: {}   # Elle çalıştırma için

permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Apply incoming files
        id: apply
        env:
          PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: |
          node - <<'NODE'
          const fs=require('fs'),path=require('path');
          const payload=JSON.parse(process.env.PAYLOAD||'{}');
          if(!Array.isArray(payload.files)) throw new Error('client_payload.files missing');
          for(const f of payload.files){
            const fp=f.path.replace(/^\/+/,'');
            fs.mkdirSync(path.dirname(fp),{recursive:true});
            const data=f.encoding==='base64'?Buffer.from(f.content,'base64'):f.content;
            fs.writeFileSync(fp,data); console.log('Wrote',fp);
          }
          NODE

      - name: Commit & push branch
        id: commit
        run: |
          set -e
          git config user.name "netfleetgpt-bot"
          git config user.email "bot@users.noreply.github.com"
          BR="netfleetgpt/${GITHUB_RUN_ID}"
          git checkout -b "$BR"
          git add -A
          if git diff --cached --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          git commit -m "NetfleetGPT: apply update $GITHUB_RUN_ID"
          git push origin "$BR"
          echo "has_changes=true" >> $GITHUB_OUTPUT

      - name: Open PR
        if: steps.commit.outputs.has_changes == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const head=`netfleetgpt/${process.env.GITHUB_RUN_ID}`;
            const base='main'; // repo default branch 'main' değilse değiştir
            const { data: pr } = await github.pulls.create({
              owner: context.repo.owner, repo: context.repo.repo,
              head, base, title: 'NetfleetGPT update',
              body: 'Automated update from NetfleetGPT.'
            });
            core.info(`PR #${pr.number} opened`);
